export const movies = [
  // Action
  {
    id: 1,
    title: "Extraction 2",
    description:
      "After barely surviving his wounds from Dhaka, Tyler Rake takes on another deadly mission: rescuing the family of a ruthless Georgian gangster from prison.",
    genre: "Action",
    rating: 7.2,
    imdbRating: 7.0,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Extraction+2",
  },
  {
    id: 2,
    title: "The Gray Man",
    description:
      "When a shadowy CIA agent uncovers damning agency secrets, he's hunted across the globe by a sociopathic rogue operative who's put a bounty on his head.",
    genre: "Action",
    rating: 6.5,
    imdbRating: 6.5,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Gray+Man",
  },
  {
    id: 3,
    title: "Red Notice",
    description:
      "An FBI profiler pursuing the world's most wanted art thief becomes his reluctant partner in crime to catch an elusive crook who's always one step ahead.",
    genre: "Action",
    rating: 6.3,
    imdbRating: 6.3,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Red+Notice",
  },
  {
    id: 4,
    title: "The Old Guard",
    description:
      "A group of immortal mercenaries with the ability to heal themselves discover someone is onto their secret, and they must fight to protect their freedom.",
    genre: "Action",
    rating: 6.7,
    imdbRating: 6.7,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Old+Guard",
  },
  {
    id: 5,
    title: "Heart of Stone",
    description:
      "An intelligence operative for a shadowy global peacekeeping agency races to stop a hacker from stealing its most valuable and dangerous weapon.",
    genre: "Action",
    rating: 5.8,
    imdbRating: 5.8,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Heart+of+Stone",
  },
  {
    id: 6,
    title: "6 Underground",
    description:
      "Six individuals from around the globe, each the very best at what they do, have been chosen for their skill and a unique desire to delete their pasts.",
    genre: "Action",
    rating: 6.1,
    imdbRating: 6.1,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=6+Underground",
  },
  {
    id: 7,
    title: "The Mother",
    description:
      "A deadly female assassin comes out of hiding to protect the daughter she gave up years before, while on the run from dangerous men.",
    genre: "Action",
    rating: 5.6,
    imdbRating: 5.6,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Mother",
  },
  {
    id: 8,
    title: "Luther: The Fallen Sun",
    description:
      "Haunted by an unsolved murder, brilliant but disgraced London police detective John Luther breaks out of prison to hunt down a sadistic serial killer.",
    genre: "Action",
    rating: 6.4,
    imdbRating: 6.3,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Luther:+The+Fallen+Sun",
  },
  {
    id: 9,
    title: "Triple Frontier",
    description:
      "Five former Special Forces operatives reunite to plan a heist in a sparsely populated multi-border zone of South America.",
    genre: "Action",
    rating: 6.4,
    imdbRating: 6.4,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Triple+Frontier",
  },
  {
    id: 10,
    title: "Rebel Moon",
    description:
      "When a peaceful settlement on the edge of a distant moon finds itself threatened by the armies of a tyrannical ruling force, a mysterious stranger becomes their best hope for survival.",
    genre: "Action",
    rating: 5.6,
    imdbRating: 5.5,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Rebel+Moon",
  },

  // Adventure
  {
    id: 81,
    title: "The Sea Beast",
    description:
      "A legendary sea monster hunter's life is turned upside down when a young girl stows away on his ship and befriends the most dangerous beast of them all.",
    genre: "Adventure",
    rating: 7.1,
    imdbRating: 7.1,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Sea+Beast",
  },
  {
    id: 82,
    title: "Slumberland",
    description:
      "A young girl discovers a secret map to the dreamworld of Slumberland, and with the help of an eccentric outlaw, she traverses dreams and flees nightmares, hoping to see her late father again.",
    genre: "Adventure",
    rating: 6.7,
    imdbRating: 6.7,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Slumberland",
  },
  {
    id: 83,
    title: "Okja",
    description:
      "A young girl risks everything to prevent a powerful, multinational company from kidnapping her best friend - a fascinating beast named Okja.",
    genre: "Adventure",
    rating: 7.3,
    imdbRating: 7.3,
    year: 2017,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Okja",
  },
  {
    id: 84,
    title: "Enola Holmes",
    description:
      "When Enola Holmes-Sherlock's teen sister-discovers her mother missing, she sets off to find her, becoming a super-sleuth in her own right as she outwits her famous brother and unravels a dangerous conspiracy around a mysterious young Lord.",
    genre: "Adventure",
    rating: 6.6,
    imdbRating: 6.6,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Enola+Holmes",
  },
  {
    id: 85,
    title: "The Lost City",
    description:
      "A reclusive romance novelist on a book tour with her cover model gets swept up in a kidnapping attempt that lands them both in a cutthroat jungle adventure.",
    genre: "Adventure",
    rating: 6.1,
    imdbRating: 6.1,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Lost+City",
  },
  {
    id: 86,
    title: "The School for Good and Evil",
    description:
      "Best friends Sophie and Agatha find themselves on opposing sides of an epic battle when they're swept away into an enchanted school where aspiring heroes and villains are trained to protect the balance between Good and Evil.",
    genre: "Adventure",
    rating: 6.0,
    imdbRating: 5.9,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=School+for+Good+and+Evil",
  },
  {
    id: 87,
    title: "Damsel",
    description:
      "A dutiful damsel agrees to marry a handsome prince, only to find the royal family has recruited her as a sacrifice to repay an ancient debt.",
    genre: "Adventure",
    rating: 6.0,
    imdbRating: 6.0,
    year: 2024,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Damsel",
  },
  {
    id: 88,
    title: "The Old Guard",
    description:
      "A covert team of immortal mercenaries is suddenly exposed and must now fight to keep their identity a secret just as an unexpected new member is discovered.",
    genre: "Adventure",
    rating: 6.7,
    imdbRating: 6.7,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Old+Guard",
  },
  {
    id: 89,
    title: "Jungle Cruise",
    description:
      "Based on Disneyland's theme park ride where a small riverboat takes a group of travelers through a jungle filled with dangerous animals and reptiles but with a supernatural element.",
    genre: "Adventure",
    rating: 6.6,
    imdbRating: 6.6,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Jungle+Cruise",
  },
  {
    id: 90,
    title: "The Witcher: Nightmare of the Wolf",
    description:
      "Escaping from poverty to become a witcher, Vesemir slays monsters for coin and glory, but when a new menace rises, he must face the demons of his past.",
    genre: "Adventure",
    rating: 7.2,
    imdbRating: 7.2,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Witcher:+Nightmare+of+the+Wolf",
  },

  // Animation
  {
    id: 91,
    title: "The Mitchells vs. the Machines",
    description:
      "A quirky, dysfunctional family's road trip is upended when they find themselves in the middle of the robot apocalypse and suddenly become humanity's unlikeliest last hope.",
    genre: "Animation",
    rating: 7.7,
    imdbRating: 7.7,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Mitchells+vs+Machines",
  },
  {
    id: 92,
    title: "Klaus",
    description:
      "A simple act of kindness always sparks another, even in a frozen, faraway place. When Smeerensburg's new postman, Jesper, befriends toymaker Klaus, their gifts melt an age-old feud and deliver a sleigh full of holiday traditions.",
    genre: "Animation",
    rating: 8.2,
    imdbRating: 8.2,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Klaus",
  },
  {
    id: 93,
    title: "Nimona",
    description:
      "A knight framed for a tragic crime teams with a shape-shifting teen to prove his innocence, but what if she's the monster he's sworn to destroy?",
    genre: "Animation",
    rating: 7.6,
    imdbRating: 7.6,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Nimona",
  },
  {
    id: 94,
    title: "The Sea Beast",
    description:
      "A legendary sea monster hunter's life is turned upside down when a young girl stows away on his ship and befriends the most dangerous beast of them all.",
    genre: "Animation",
    rating: 7.1,
    imdbRating: 7.1,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Sea+Beast",
  },
  {
    id: 95,
    title: "Over the Moon",
    description:
      "In this animated musical, a girl builds a rocket ship and blasts off, hoping to meet a mythical moon goddess.",
    genre: "Animation",
    rating: 6.4,
    imdbRating: 6.4,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Over+the+Moon",
  },
  {
    id: 96,
    title: "Wendell & Wild",
    description:
      "Two scheming demon brothers, Wendell and Wild, enlist the aid of 13-year-old Kat Elliot to summon them to the Land of the Living.",
    genre: "Animation",
    rating: 6.3,
    imdbRating: 6.3,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Wendell+and+Wild",
  },
  {
    id: 97,
    title: "The Willoughbys",
    description:
      "Convinced they'd be better off raising themselves, the Willoughby children hatch a sneaky plan to send their selfish parents on vacation. The siblings then embark on their own high-flying adventure to find the true meaning of family.",
    genre: "Animation",
    rating: 6.4,
    imdbRating: 6.4,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Willoughbys",
  },
  {
    id: 98,
    title: "Wish Dragon",
    description:
      "Determined teen Din is longing to reconnect with his childhood best friend when he meets a wish-granting dragon who shows him the magic of possibilities.",
    genre: "Animation",
    rating: 7.2,
    imdbRating: 7.2,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Wish+Dragon",
  },
  {
    id: 99,
    title: "Vivo",
    description:
      "A music-loving kinkajou embarks on the journey of a lifetime to fulfill his destiny and deliver a love song for an old friend.",
    genre: "Animation",
    rating: 6.7,
    imdbRating: 6.7,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Vivo",
  },
  {
    id: 100,
    title: "Apollo 10½: A Space Age Childhood",
    description:
      "A coming-of-age story set in the suburbs of Houston, Texas in the summer of 1969, centered around the historic Apollo 11 moon landing.",
    genre: "Animation",
    rating: 7.3,
    imdbRating: 7.3,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Apollo+10+1/2",
  },

  // Comedy
  {
    id: 11,
    title: "Don't Look Up",
    description:
      "Two low-level astronomers must go on a giant media tour to warn mankind of an approaching comet that will destroy planet Earth.",
    genre: "Comedy",
    rating: 7.2,
    imdbRating: 7.2,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Don't+Look+Up",
  },
  {
    id: 12,
    title: "Murder Mystery 2",
    description:
      "Nick and Audrey Spitz are now full-time detectives struggling to get their private eye agency off the ground when they're invited to celebrate the wedding of their friend the Maharaja on his private island.",
    genre: "Comedy",
    rating: 5.7,
    imdbRating: 5.7,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Murder+Mystery+2",
  },
  {
    id: 13,
    title: "The Adam Project",
    description:
      "After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self for a mission to save the future.",
    genre: "Comedy",
    rating: 6.7,
    imdbRating: 6.7,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Adam+Project",
  },
  {
    id: 14,
    title: "You People",
    description:
      "Follows a new couple and their families, who find themselves examining modern love and family dynamics amidst clashing cultures, societal expectations and generational differences.",
    genre: "Comedy",
    rating: 5.5,
    imdbRating: 5.5,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=You+People",
  },
  {
    id: 15,
    title: "The Out-Laws",
    description:
      "A straight-laced bank manager about to marry the love of his life. When his bank is held up by infamous Ghost Bandits during his wedding week, he believes his future in-laws who just arrived in town, are the infamous Out-Laws.",
    genre: "Comedy",
    rating: 5.5,
    imdbRating: 5.4,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Out-Laws",
  },
  {
    id: 16,
    title: "Your Place or Mine",
    description:
      "Two long-distance best friends change each other's lives when she decides to pursue a lifelong dream and he volunteers to keep an eye on her teenage son.",
    genre: "Comedy",
    rating: 5.7,
    imdbRating: 5.6,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Your+Place+or+Mine",
  },
  {
    id: 17,
    title: "Players",
    description:
      "New York sportswriter Mack has spent years devising successful hook-up 'plays' with her friends, but when she unexpectedly falls for one of her targets, she must learn what it takes to go from simply scoring to playing for keeps.",
    genre: "Comedy",
    rating: 5.5,
    imdbRating: 5.6,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Players",
  },
  {
    id: 18,
    title: "Family Switch",
    description:
      "When the Walker family members switch bodies with each other during a rare planetary alignment, their hilarious journey to find their way back to normal will bring them closer together than they ever thought possible.",
    genre: "Comedy",
    rating: 5.7,
    imdbRating: 5.7,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Family+Switch",
  },
  {
    id: 19,
    title: "Lift",
    description:
      "An international heist crew, led by Cyrus Whitaker, races to lift $500 million in gold from a passenger plane at 40,000 feet.",
    genre: "Comedy",
    rating: 5.4,
    imdbRating: 5.3,
    year: 2024,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Lift",
  },
  {
    id: 20,
    title: "The Lovebirds",
    description:
      "A couple experiences a defining moment in their relationship when they are unintentionally embroiled in a murder mystery.",
    genre: "Comedy",
    rating: 6.1,
    imdbRating: 6.1,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Lovebirds",
  },

  // Crime
  {
    id: 101,
    title: "The Irishman",
    description:
      "Hitman Frank Sheeran looks back at the secrets he kept as a loyal member of the Bufalino crime family in this acclaimed film from Martin Scorsese.",
    genre: "Crime",
    rating: 7.8,
    imdbRating: 7.8,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Irishman",
  },
  {
    id: 102,
    title: "The Gentlemen",
    description:
      "An American expat tries to sell off his highly profitable marijuana empire in London, triggering plots, schemes, bribery and blackmail in an attempt to steal his domain out from under him.",
    genre: "Crime",
    rating: 7.8,
    imdbRating: 7.8,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Gentlemen",
  },
  {
    id: 103,
    title: "The Guilty",
    description:
      "A demoted police officer assigned to a call dispatch desk is conflicted when he receives an emergency phone call from a kidnapped woman.",
    genre: "Crime",
    rating: 6.3,
    imdbRating: 6.3,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Guilty",
  },
  {
    id: 104,
    title: "The Highwaymen",
    description: "A pair of Texas Rangers come out of retirement to catch the infamous outlaws Bonnie and Clyde.",
    genre: "Crime",
    rating: 6.9,
    imdbRating: 6.9,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Highwaymen",
  },
  {
    id: 105,
    title: "Spenser Confidential",
    description:
      "When two Boston police officers are murdered, ex-cop Spenser teams up with his no-nonsense roommate, Hawk, to take down criminals.",
    genre: "Crime",
    rating: 6.2,
    imdbRating: 6.2,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Spenser+Confidential",
  },
  {
    id: 106,
    title: "The Laundromat",
    description:
      "A widow investigates an insurance fraud, chasing leads to a pair of Panama City law partners exploiting the world's financial system.",
    genre: "Crime",
    rating: 6.3,
    imdbRating: 6.3,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Laundromat",
  },
  {
    id: 107,
    title: "The Last Thing He Wanted",
    description:
      "A veteran D.C. journalist loses the thread of her own narrative when a guilt-propelled errand for her father thrusts her from byline to unwitting subject in the very story she's trying to break.",
    genre: "Crime",
    rating: 4.3,
    imdbRating: 4.3,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Last+Thing+He+Wanted",
  },
  {
    id: 108,
    title: "Polar",
    description:
      "A retiring assassin suddenly finds himself on the receiving end of a hit, contracted by none other than his own employer seeking to cash in on the pensions of aging employees.",
    genre: "Crime",
    rating: 6.3,
    imdbRating: 6.3,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Polar",
  },
  {
    id: 109,
    title: "The Outsider",
    description:
      "An American soldier imprisoned in postwar Japan enters the dark world of the yakuza, adopting their way of life in repayment for his freedom.",
    genre: "Crime",
    rating: 6.3,
    imdbRating: 6.3,
    year: 2018,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Outsider",
  },
  {
    id: 110,
    title: "Killers of the Flower Moon",
    description:
      "Members of the Osage tribe in the United States are murdered under mysterious circumstances in the 1920s, sparking a major F.B.I. investigation.",
    genre: "Crime",
    rating: 7.7,
    imdbRating: 7.7,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Killers+of+the+Flower+Moon",
  },

  // Documentary
  {
    id: 61,
    title: "My Octopus Teacher",
    description:
      "A filmmaker forges an unusual friendship with an octopus living in a South African kelp forest, learning as the animal shares the mysteries of her world.",
    genre: "Documentary",
    rating: 8.1,
    imdbRating: 8.1,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=My+Octopus+Teacher",
  },
  {
    id: 62,
    title: "The Social Dilemma",
    description:
      "This documentary-drama hybrid explores the dangerous human impact of social networking, with tech experts sounding the alarm on their own creations.",
    genre: "Documentary",
    rating: 7.6,
    imdbRating: 7.6,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Social+Dilemma",
  },
  {
    id: 63,
    title: "Tiger King",
    description:
      "A zoo owner spirals out of control amid a cast of eccentric characters in this true murder-for-hire story from the underworld of big cat breeding.",
    genre: "Documentary",
    rating: 7.5,
    imdbRating: 7.5,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Tiger+King",
  },
  {
    id: 64,
    title: "Seaspiracy",
    description:
      "Passionate about ocean life, a filmmaker sets out to document the harm that humans do to marine species - and uncovers alarming global corruption.",
    genre: "Documentary",
    rating: 8.0,
    imdbRating: 8.0,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Seaspiracy",
  },
  {
    id: 65,
    title: "Formula 1: Drive to Survive",
    description:
      "Drivers, managers and team owners live life in the fast lane — both on and off the track — during each cutthroat season of Formula 1 racing.",
    genre: "Documentary",
    rating: 8.6,
    imdbRating: 8.5,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Formula+1",
  },
  {
    id: 66,
    title: "The Last Dance",
    description:
      "This docuseries chronicles the rise of superstar Michael Jordan and the 1990s Chicago Bulls, with unaired footage from the 1997-98 season.",
    genre: "Documentary",
    rating: 9.0,
    imdbRating: 9.1,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Last+Dance",
  },
  {
    id: 67,
    title: "Making A Murderer",
    description:
      "Filmed over a 10-year period, this real-life thriller follows the unprecedented story of two men accused of a grisly crime they may not have committed.",
    genre: "Documentary",
    rating: 8.5,
    imdbRating: 8.5,
    year: 2015,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Making+A+Murderer",
  },
  {
    id: 68,
    title: "Icarus",
    description:
      "While investigating the furtive world of illegal doping in sports, director Bryan Fogel connects with a Russian scientist who reveals a vast international doping conspiracy.",
    genre: "Documentary",
    rating: 7.9,
    imdbRating: 7.9,
    year: 2017,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Icarus",
  },
  {
    id: 69,
    title: "Untold: Malice at the Palace",
    description:
      "A comprehensive look at the infamous 2004 Pacers-Pistons brawl led by Metta World Peace (formerly Ron Artest) with never-before-seen footage and revealing interviews.",
    genre: "Documentary",
    rating: 7.5,
    imdbRating: 7.5,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Untold",
  },
  {
    id: 70,
    title: "Our Planet",
    description:
      "Experience our planet's natural beauty and examine how climate change impacts all living creatures in this ambitious documentary of spectacular scope.",
    genre: "Documentary",
    rating: 9.2,
    imdbRating: 9.3,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Our+Planet",
  },

  // Drama
  {
    id: 21,
    title: "The Irishman",
    description:
      "Hitman Frank Sheeran looks back at the secrets he kept as a loyal member of the Bufalino crime family in this acclaimed film from Martin Scorsese.",
    genre: "Drama",
    rating: 7.8,
    imdbRating: 7.8,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Irishman",
  },
  {
    id: 22,
    title: "Marriage Story",
    description:
      "Academy Award-nominated filmmaker Noah Baumbach directs this incisive and compassionate look at a marriage coming apart and a family staying together.",
    genre: "Drama",
    rating: 7.9,
    imdbRating: 7.9,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Marriage+Story",
  },
  {
    id: 23,
    title: "The Trial of the Chicago 7",
    description:
      "What was supposed to be a peaceful protest turned into a violent clash with the police. What followed was one of the most notorious trials in history.",
    genre: "Drama",
    rating: 7.8,
    imdbRating: 7.7,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Trial+of+the+Chicago+7",
  },
  {
    id: 24,
    title: "The Power of the Dog",
    description:
      "Charismatic rancher Phil Burbank inspires fear and awe in those around him. When his brother brings home a new wife and her son, Phil torments them until he finds himself exposed to the possibility of love.",
    genre: "Drama",
    rating: 6.9,
    imdbRating: 6.8,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Power+of+the+Dog",
  },
  {
    id: 25,
    title: "Rustin",
    description:
      "In 1963, activist Bayard Rustin faced racism and homophobia as he helped change the course of Civil Rights history by orchestrating the March on Washington.",
    genre: "Drama",
    rating: 6.9,
    imdbRating: 6.7,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Rustin",
  },
  {
    id: 26,
    title: "Nyad",
    description:
      "The remarkable true story of athlete Diana Nyad who, at age 60 and with the help of her best friend and coach, commits to achieving her life-long dream: a 110-mile open ocean swim from Cuba to Florida.",
    genre: "Drama",
    rating: 7.2,
    imdbRating: 7.2,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Nyad",
  },
  {
    id: 27,
    title: "The Dig",
    description:
      "On the eve of World War II, a British widow hires a self-taught archaeologist to dig up mysterious formations on her land, leading to a staggering find.",
    genre: "Drama",
    rating: 7.1,
    imdbRating: 7.1,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Dig",
  },
  {
    id: 28,
    title: "Leave the World Behind",
    description:
      "A family's getaway to a luxury rental home takes an ominous turn when a cyberattack knocks out their devices, and two strangers appear at their door.",
    genre: "Drama",
    rating: 6.5,
    imdbRating: 6.5,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Leave+the+World+Behind",
  },
  {
    id: 29,
    title: "Maestro",
    description:
      "This film from director and star Bradley Cooper portrays the lifelong relationship between Leonard Bernstein and Felicia Montealegre Cohn Bernstein.",
    genre: "Drama",
    rating: 6.8,
    imdbRating: 6.7,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Maestro",
  },
  {
    id: 30,
    title: "May December",
    description:
      "Twenty years after their notorious tabloid romance, a married couple buckles under the pressure when an actress arrives to do research for a film about their past.",
    genre: "Drama",
    rating: 7.2,
    imdbRating: 7.1,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=May+December",
  },

  // Family
  {
    id: 111,
    title: "The Christmas Chronicles",
    description:
      "The story of sister and brother, Kate and Teddy Pierce, whose Christmas Eve plan to catch Santa Claus on camera turns into an unexpected journey that most kids could only dream about.",
    genre: "Family",
    rating: 7.0,
    imdbRating: 7.0,
    year: 2018,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Christmas+Chronicles",
  },
  {
    id: 112,
    title: "We Can Be Heroes",
    description:
      "When alien invaders capture Earth's superheroes, their kids must learn to work together to save their parents - and the planet.",
    genre: "Family",
    rating: 4.7,
    imdbRating: 4.7,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=We+Can+Be+Heroes",
  },
  {
    id: 113,
    title: "Finding 'Ohana",
    description:
      "A summer in rural O'ahu takes an exciting turn for two Brooklyn-raised siblings when a journal pointing to long-lost treasure sets them on an epic adventure with new friends, and leads them to reconnect with their Hawaiian heritage.",
    genre: "Family",
    rating: 6.1,
    imdbRating: 6.1,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Finding+Ohana",
  },
  {
    id: 114,
    title: "Yes Day",
    description:
      "A mom and dad who usually say no decide to say yes to their kids' wildest requests with a few ground rules on a whirlwind day of fun and adventure.",
    genre: "Family",
    rating: 5.7,
    imdbRating: 5.7,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Yes+Day",
  },
  {
    id: 115,
    title: "The Main Event",
    description:
      "After discovering a magical mask, an 11-year-old aspiring wrestler enters a competition to become the next WWE superstar by using special powers from a magical mask.",
    genre: "Family",
    rating: 4.9,
    imdbRating: 4.9,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Main+Event",
  },
  {
    id: 116,
    title: "A Boy Called Christmas",
    description:
      "In this origin story of Father Christmas, an ordinary boy (with a loyal pet mouse and a reindeer at his side) sets out on an extraordinary adventure to find his father who is on a quest to discover the fabled village of Elfhelm.",
    genre: "Family",
    rating: 6.7,
    imdbRating: 6.7,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=A+Boy+Called+Christmas",
  },
  {
    id: 117,
    title: "Slumberland",
    description:
      "A young girl discovers a secret map to the dreamworld of Slumberland, and with the help of an eccentric outlaw, she traverses dreams and flees nightmares, hoping to see her late father again.",
    genre: "Family",
    rating: 6.7,
    imdbRating: 6.7,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Slumberland",
  },
  {
    id: 118,
    title: "The Sleepover",
    description:
      "When two siblings discover their seemingly normal mom is a former thief in witness protection who has been forced to pull one last job, they team up to rescue her over the course of an action-packed night.",
    genre: "Family",
    rating: 5.6,
    imdbRating: 5.6,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Sleepover",
  },
  {
    id: 119,
    title: "Tall Girl",
    description:
      "Jodi, the tallest girl in her high school, has always felt uncomfortable in her own skin. But after years of slouching, being made fun of, and avoiding attention at all costs, Jodi finally decides to find the confidence to stand tall.",
    genre: "Family",
    rating: 5.2,
    imdbRating: 5.2,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Tall+Girl",
  },
  {
    id: 120,
    title: "Feel the Beat",
    description:
      "After failing to find success on Broadway, April returns to her hometown and reluctantly begins coaching a group of young misfits for a dance competition.",
    genre: "Family",
    rating: 6.3,
    imdbRating: 6.3,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Feel+the+Beat",
  },

  // Fantasy
  {
    id: 121,
    title: "The School for Good and Evil",
    description:
      "Best friends Sophie and Agatha find themselves on opposing sides of an epic battle when they're swept away into an enchanted school where aspiring heroes and villains are trained to protect the balance between Good and Evil.",
    genre: "Fantasy",
    rating: 6.0,
    imdbRating: 5.9,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=School+for+Good+and+Evil",
  },
  {
    id: 122,
    title: "Bright",
    description:
      "In an alternate present where humans and fantasy creatures have co-existed since the beginning of time, a human cop and his orc partner stumble on a powerful object and become embroiled in a prophesied turf war.",
    genre: "Fantasy",
    rating: 6.3,
    imdbRating: 6.3,
    year: 2017,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Bright",
  },
  {
    id: 123,
    title: "Damsel",
    description:
      "A dutiful damsel agrees to marry a handsome prince, only to find the royal family has recruited her as a sacrifice to repay an ancient debt.",
    genre: "Fantasy",
    rating: 6.0,
    imdbRating: 6.0,
    year: 2024,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Damsel",
  },
  {
    id: 124,
    title: "The Old Guard",
    description:
      "A covert team of immortal mercenaries is suddenly exposed and must now fight to keep their identity a secret just as an unexpected new member is discovered.",
    genre: "Fantasy",
    rating: 6.7,
    imdbRating: 6.7,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Old+Guard",
  },
  {
    id: 125,
    title: "Slumberland",
    description:
      "A young girl discovers a secret map to the dreamworld of Slumberland, and with the help of an eccentric outlaw, she traverses dreams and flees nightmares, hoping to see her late father again.",
    genre: "Fantasy",
    rating: 6.7,
    imdbRating: 6.7,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Slumberland",
  },
  {
    id: 126,
    title: "The Witcher: Nightmare of the Wolf",
    description:
      "Escaping from poverty to become a witcher, Vesemir slays monsters for coin and glory, but when a new menace rises, he must face the demons of his past.",
    genre: "Fantasy",
    rating: 7.2,
    imdbRating: 7.2,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Witcher:+Nightmare+of+the+Wolf",
  },
  {
    id: 127,
    title: "A Babysitter's Guide to Monster Hunting",
    description: "A babysitter embarks on a mission to save a child who's been abducted by monsters.",
    genre: "Fantasy",
    rating: 5.4,
    imdbRating: 5.4,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Babysitter's+Guide",
  },
  {
    id: 128,
    title: "Nightbooks",
    description:
      "Follows a boy named Alex who becomes the prisoner of an evil witch in her contemporary New York City apartment.",
    genre: "Fantasy",
    rating: 5.7,
    imdbRating: 5.7,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Nightbooks",
  },
  {
    id: 129,
    title: "The Water Man",
    description:
      "A boy sets out on a quest to save his ill mother by searching for a mythic figure said to have magical healing powers.",
    genre: "Fantasy",
    rating: 5.8,
    imdbRating: 5.8,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Water+Man",
  },
  {
    id: 130,
    title: "The Curse of Bridge Hollow",
    description:
      "A father and his teenage daughter are forced to team up and save their town after an ancient and mischievous spirit causes Halloween decorations to come to life and wreak havoc.",
    genre: "Fantasy",
    rating: 5.5,
    imdbRating: 5.5,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Curse+of+Bridge+Hollow",
  },

  // Horror
  {
    id: 31,
    title: "Bird Box",
    description:
      "Five years after an ominous unseen presence drives most of society to suicide, a survivor and her two children make a desperate bid to reach safety.",
    genre: "Horror",
    rating: 6.6,
    imdbRating: 6.6,
    year: 2018,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Bird+Box",
  },
  {
    id: 32,
    title: "The Platform",
    description:
      "A vertical prison with one cell per level. Two people per cell. Only one food platform and two minutes per day to feed. An endless nightmare trapped in The Pit.",
    genre: "Horror",
    rating: 7.0,
    imdbRating: 7.0,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Platform",
  },
  {
    id: 33,
    title: "His House",
    description:
      "A refugee couple makes a harrowing escape from war-torn South Sudan, but then they struggle to adjust to their new life in an English town that has an evil lurking beneath the surface.",
    genre: "Horror",
    rating: 6.5,
    imdbRating: 6.5,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=His+House",
  },
  {
    id: 34,
    title: "Fear Street Trilogy",
    description:
      "A trilogy of films set in 1994, 1978, and 1666, telling the story of a group of teenagers who discover the terrifying events that have haunted their town for generations.",
    genre: "Horror",
    rating: 6.7,
    imdbRating: 6.6,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Fear+Street+Trilogy",
  },
  {
    id: 35,
    title: "The Ritual",
    description:
      "A group of college friends reunite for a trip to the forest, but encounter a menacing presence in the woods that's stalking them.",
    genre: "Horror",
    rating: 6.3,
    imdbRating: 6.3,
    year: 2017,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Ritual",
  },
  {
    id: 36,
    title: "Alive",
    description:
      "The rapid spread of an unknown infection has left an entire city in ungovernable chaos, but one survivor remains alive in isolation.",
    genre: "Horror",
    rating: 6.2,
    imdbRating: 6.2,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Alive",
  },
  {
    id: 37,
    title: "Choose or Die",
    description:
      "After firing up a lost 80s survival horror game, a young coder unleashes a hidden curse that tears reality apart, forcing her to make terrifying decisions and face deadly consequences.",
    genre: "Horror",
    rating: 4.8,
    imdbRating: 4.8,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Choose+or+Die",
  },
  {
    id: 38,
    title: "No One Gets Out Alive",
    description:
      "An immigrant in search of the American dream is forced to take a room in a boarding house, where she finds herself in a nightmare she can't escape.",
    genre: "Horror",
    rating: 5.3,
    imdbRating: 5.3,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=No+One+Gets+Out+Alive",
  },
  {
    id: 39,
    title: "In the Tall Grass",
    description:
      "After hearing a young boy's cry for help, a sister and brother venture into a vast field of tall grass in Kansas but soon discover there may be no way out...and that something evil lurks within.",
    genre: "Horror",
    rating: 5.4,
    imdbRating: 5.4,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=In+the+Tall+Grass",
  },
  {
    id: 40,
    title: "Cadaver",
    description:
      "After a nuclear disaster, a starving family is lured by the offer of a meal to participate in a play at a hotel, where audience members begin to vanish.",
    genre: "Horror",
    rating: 5.1,
    imdbRating: 5.1,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Cadaver",
  },

  // Music
  {
    id: 131,
    title: "Tick, Tick... Boom!",
    description:
      "On the cusp of his 30th birthday, a promising young theater composer navigates love, friendship and the pressures of life as an artist in New York City.",
    genre: "Music",
    rating: 7.5,
    imdbRating: 7.5,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Tick+Tick+Boom",
  },
  {
    id: 132,
    title: "The Dirt",
    description: "The story of how Mötley Crüe came to be one of the most notorious rock 'n roll groups in history.",
    genre: "Music",
    rating: 7.0,
    imdbRating: 7.0,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Dirt",
  },
  {
    id: 133,
    title: "Eurovision Song Contest: The Story of Fire Saga",
    description:
      "When aspiring musicians Lars and Sigrit are given the opportunity to represent their country at the world's biggest song competition, they finally have a chance to prove that any dream worth having is a dream worth fighting for.",
    genre: "Music",
    rating: 6.5,
    imdbRating: 6.5,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Eurovision",
  },
  {
    id: 134,
    title: "Ma Rainey's Black Bottom",
    description:
      "Tensions rise when the trailblazing Mother of the Blues and her band gather at a Chicago recording studio in 1927. Adapted from August Wilson's play.",
    genre: "Music",
    rating: 6.9,
    imdbRating: 6.9,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Ma+Rainey",
  },
  {
    id: 135,
    title: "Roxanne Roxanne",
    description:
      'In the early 1980s, the most feared battle MC in Queens, New York, was a fierce teenage girl with the weight of the world on her shoulders. At the age of 14, Lolita "Roxanne Shanté" Gooden was well on her way to becoming a hip-hop legend.',
    genre: "Music",
    rating: 6.1,
    imdbRating: 6.1,
    year: 2017,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Roxanne+Roxanne",
  },
  {
    id: 136,
    title: "The Prom",
    description:
      "A troupe of hilariously self-obsessed theater stars swarm into a small conservative Indiana town in support of a high school girl who wants to take her girlfriend to the prom.",
    genre: "Music",
    rating: 5.9,
    imdbRating: 5.9,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Prom",
  },
  {
    id: 137,
    title: "Been So Long",
    description:
      "A dedicated single mother who, on a rare night on the town, is charmed by a handsome yet troubled stranger.",
    genre: "Music",
    rating: 5.5,
    imdbRating: 5.5,
    year: 2018,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Been+So+Long",
  },
  {
    id: 138,
    title: "Maestro",
    description:
      "This film from director and star Bradley Cooper portrays the lifelong relationship between Leonard Bernstein and Felicia Montealegre Cohn Bernstein.",
    genre: "Music",
    rating: 6.8,
    imdbRating: 6.7,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Maestro",
  },
  {
    id: 139,
    title: "BLACKPINK: Light Up the Sky",
    description:
      "Record-shattering Korean girl band BLACKPINK tell their story — and detail the hard fought journey of the dreams and trials behind their meteoric rise to fame.",
    genre: "Music",
    rating: 7.6,
    imdbRating: 7.6,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=BLACKPINK",
  },
  {
    id: 140,
    title: "Homecoming: A Film by Beyoncé",
    description:
      "This intimate, in-depth look at Beyoncé's celebrated 2018 Coachella performance reveals the emotional road from creative concept to cultural movement.",
    genre: "Music",
    rating: 7.5,
    imdbRating: 7.5,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Homecoming",
  },

  // Mystery
  {
    id: 141,
    title: "Glass Onion: A Knives Out Mystery",
    description:
      "Tech billionaire Miles Bron invites his friends for a getaway on his private Greek island. When someone turns up dead, Detective Benoit Blanc is put on the case.",
    genre: "Mystery",
    rating: 7.1,
    imdbRating: 7.1,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Glass+Onion",
  },
  {
    id: 142,
    title: "The Woman in the Window",
    description:
      "An agoraphobic woman living alone in New York begins spying on her new neighbors, only to witness a disturbing act of violence.",
    genre: "Mystery",
    rating: 5.7,
    imdbRating: 5.7,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Woman+in+the+Window",
  },
  {
    id: 143,
    title: "Murder Mystery",
    description:
      "A New York cop and his wife go on a European vacation to reinvigorate the spark in their marriage, but end up getting framed and on the run for the death of an elderly billionaire.",
    genre: "Mystery",
    rating: 6.0,
    imdbRating: 6.0,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Murder+Mystery",
  },
  {
    id: 144,
    title: "Enola Holmes",
    description:
      "When Enola Holmes-Sherlock's teen sister-discovers her mother missing, she sets off to find her, becoming a super-sleuth in her own right as she outwits her famous brother and unravels a dangerous conspiracy around a mysterious young Lord.",
    genre: "Mystery",
    rating: 6.6,
    imdbRating: 6.6,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Enola+Holmes",
  },
  {
    id: 145,
    title: "The Pale Blue Eye",
    description:
      "A world-weary detective is hired to investigate the murder of a West Point cadet. Stymied by the cadets' code of silence, he enlists one of their own to help unravel the case - a young man the world would come to know as Edgar Allan Poe.",
    genre: "Mystery",
    rating: 6.6,
    imdbRating: 6.6,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Pale+Blue+Eye",
  },
  {
    id: 146,
    title: "Rebecca",
    description:
      "A young newlywed arrives at her husband's imposing family estate on a windswept English coast and finds herself battling the shadow of his first wife, Rebecca, whose legacy lives on in the house long after her death.",
    genre: "Mystery",
    rating: 6.1,
    imdbRating: 6.1,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Rebecca",
  },
  {
    id: 147,
    title: "The Devil All the Time",
    description:
      "Sinister characters converge around a young man devoted to protecting those he loves in a postwar backwoods town teeming with corruption and brutality.",
    genre: "Mystery",
    rating: 7.1,
    imdbRating: 7.1,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Devil+All+the+Time",
  },
  {
    id: 148,
    title: "Things Heard & Seen",
    description:
      "An artist relocates to the Hudson Valley and begins to suspect that her marriage has a sinister darkness, one that rivals her new home's history.",
    genre: "Mystery",
    rating: 5.3,
    imdbRating: 5.3,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Things+Heard+and+Seen",
  },
  {
    id: 149,
    title: "The Guilty",
    description:
      "A demoted police officer assigned to a call dispatch desk is conflicted when he receives an emergency phone call from a kidnapped woman.",
    genre: "Mystery",
    rating: 6.3,
    imdbRating: 6.3,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Guilty",
  },
  {
    id: 150,
    title: "Lost Girls",
    description:
      "When Mari Gilbert's daughter disappears, police inaction drives her own investigation into the gated Long Island community where Shannan was last seen. Her search brings attention to over a dozen murdered sex workers.",
    genre: "Mystery",
    rating: 6.1,
    imdbRating: 6.1,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Lost+Girls",
  },

  // Romance
  {
    id: 51,
    title: "To All the Boys I've Loved Before",
    description: "A teenage girl's secret love letters are exposed and wreak havoc on her love life.",
    genre: "Romance",
    rating: 7.1,
    imdbRating: 7.0,
    year: 2018,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=To+All+the+Boys",
  },
  {
    id: 52,
    title: "Always Be My Maybe",
    description:
      "Everyone assumed Sasha and Marcus would wind up together except for Sasha and Marcus. Reconnecting after 15 years, the two start to wonder... maybe?",
    genre: "Romance",
    rating: 6.8,
    imdbRating: 6.8,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Always+Be+My+Maybe",
  },
  {
    id: 53,
    title: "Your Place or Mine",
    description:
      "Two long-distance best friends change each other's lives when she decides to pursue a lifelong dream and he volunteers to keep an eye on her teenage son.",
    genre: "Romance",
    rating: 5.7,
    imdbRating: 5.6,
    year: 2023,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Your+Place+or+Mine",
  },
  {
    id: 54,
    title: "Set It Up",
    description: "Two corporate executive assistants hatch a plan to match-make their two bosses.",
    genre: "Romance",
    rating: 6.5,
    imdbRating: 6.5,
    year: 2018,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Set+It+Up",
  },
  {
    id: 55,
    title: "The Half of It",
    description:
      "When smart but cash-strapped teen Ellie Chu agrees to write a love letter for a jock, she doesn't expect to become his friend - or fall for his crush.",
    genre: "Romance",
    rating: 6.9,
    imdbRating: 6.9,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Half+of+It",
  },
  {
    id: 56,
    title: "The Kissing Booth",
    description:
      "A high school student finds herself face-to-face with her long-term crush when she signs up to run a kissing booth at the spring carnival.",
    genre: "Romance",
    rating: 6.0,
    imdbRating: 6.0,
    year: 2018,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Kissing+Booth",
  },
  {
    id: 57,
    title: "Love Hard",
    description:
      "After meeting her perfect match on a dating app, an LA writer learns she's been catfished when she flies 3,000 miles to surprise him for Christmas.",
    genre: "Romance",
    rating: 6.3,
    imdbRating: 6.3,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Love+Hard",
  },
  {
    id: 58,
    title: "A Perfect Pairing",
    description:
      "To win over a major client, a go-getter LA wine company exec signs on to work at an Australian sheep farm, where she sparks with a rugged and mysterious local.",
    genre: "Romance",
    rating: 6.1,
    imdbRating: 6.1,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=A+Perfect+Pairing",
  },
  {
    id: 59,
    title: "Purple Hearts",
    description:
      "An aspiring musician agrees to a marriage of convenience with a soon-to-deploy Marine, but a tragedy soon turns their fake relationship all too real.",
    genre: "Romance",
    rating: 6.7,
    imdbRating: 6.7,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Purple+Hearts",
  },
  {
    id: 60,
    title: "Through My Window",
    description:
      "Raquel's longtime crush on her next-door neighbor turns into something more when he starts developing feelings for her, despite his family's objections.",
    genre: "Romance",
    rating: 5.7,
    imdbRating: 5.6,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Through+My+Window",
  },

  // Sci-Fi
  {
    id: 41,
    title: "The Adam Project",
    description:
      "After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self for a mission to save the future.",
    genre: "Sci-Fi",
    rating: 6.7,
    imdbRating: 6.7,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Adam+Project",
  },
  {
    id: 42,
    title: "The Midnight Sky",
    description:
      "This post-apocalyptic tale follows Augustine, a lonely scientist in the Arctic, as he races to stop Sully and her fellow astronauts from returning home to a mysterious global catastrophe.",
    genre: "Sci-Fi",
    rating: 5.6,
    imdbRating: 5.6,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Midnight+Sky",
  },
  {
    id: 43,
    title: "Oxygen",
    description:
      "A woman wakes up in a cryogenic unit with no memory. Quickly running out of oxygen, she must find a way to remember who she is in order to survive.",
    genre: "Sci-Fi",
    rating: 6.5,
    imdbRating: 6.5,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Oxygen",
  },
  {
    id: 44,
    title: "I Am Mother",
    description:
      "In the wake of humanity's extinction, a teenage girl is raised by a robot designed to repopulate the earth. But their unique bond is threatened when an inexplicable stranger arrives with alarming news.",
    genre: "Sci-Fi",
    rating: 6.7,
    imdbRating: 6.7,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=I+Am+Mother",
  },
  {
    id: 45,
    title: "Space Sweepers",
    description:
      "Set in 2092, spaceship Victory is one of the many that live off salvaging space debris. Crewed with a genius space pilot, a mysterious ex-space pirate, a spaceship engineer, and a reprogrammed military robot, Victory surpasses all other space sweepers.",
    genre: "Sci-Fi",
    rating: 6.6,
    imdbRating: 6.6,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Space+Sweepers",
  },
  {
    id: 46,
    title: "Stowaway",
    description:
      "A three-person crew on a mission to Mars faces an impossible choice when an unplanned passenger jeopardizes the lives of everyone on board.",
    genre: "Sci-Fi",
    rating: 5.6,
    imdbRating: 5.6,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Stowaway",
  },
  {
    id: 47,
    title: "The Cloverfield Paradox",
    description:
      "Orbiting a planet on the brink of war, scientists test a device to solve an energy crisis, and end up face-to-face with a dark alternate reality.",
    genre: "Sci-Fi",
    rating: 5.5,
    imdbRating: 5.5,
    year: 2018,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Cloverfield+Paradox",
  },
  {
    id: 48,
    title: "Outside the Wire",
    description:
      "In the near future, a drone pilot sent into a war zone finds himself paired with a top-secret android officer on a mission to stop a nuclear attack.",
    genre: "Sci-Fi",
    rating: 5.4,
    imdbRating: 5.4,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Outside+the+Wire",
  },
  {
    id: 49,
    title: "Extinction",
    description:
      "A father has a recurring dream of losing his family. His nightmare turns into reality when the planet is invaded by a force bent on destruction. Fighting for their lives, he comes to realize an unknown strength to keep them safe from harm.",
    genre: "Sci-Fi",
    rating: 5.8,
    imdbRating: 5.8,
    year: 2018,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Extinction",
  },
  {
    id: 50,
    title: "Project Power",
    description:
      "When a pill that gives its users unpredictable superpowers for five minutes hits the streets of New Orleans, a teenage dealer and a local cop must team with an ex-soldier to take down the group responsible for its creation.",
    genre: "Sci-Fi",
    rating: 6.0,
    imdbRating: 6.0,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Project+Power",
  },

  // Thriller
  {
    id: 71,
    title: "The Woman in the Window",
    description:
      "An agoraphobic woman living alone in New York begins spying on her new neighbors, only to witness a disturbing act of violence.",
    genre: "Thriller",
    rating: 5.7,
    imdbRating: 5.7,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Woman+in+the+Window",
  },
  {
    id: 72,
    title: "Fractured",
    description:
      "A couple stops at a gas station, where their 6 y.o. daughter's arm is fractured. They hurry to a hospital. Something strange is going on there. The wife and daughter go missing.",
    genre: "Thriller",
    rating: 6.4,
    imdbRating: 6.4,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Fractured",
  },
  {
    id: 73,
    title: "The Guilty",
    description:
      "A troubled police detective demoted to 911 operator duty scrambles to save a distressed caller during a harrowing day of revelations — and reckonings.",
    genre: "Thriller",
    rating: 6.3,
    imdbRating: 6.3,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Guilty",
  },
  {
    id: 74,
    title: "Calibre",
    description: "A shocking deed committed by two old friends comes back to haunt them.",
    genre: "Thriller",
    rating: 6.8,
    imdbRating: 6.8,
    year: 2018,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Calibre",
  },
  {
    id: 75,
    title: "Gerald's Game",
    description:
      "When her husband's sex game goes wrong, Jessie -- handcuffed to a bed in a remote lake house -- faces warped visions, dark secrets and a dire choice.",
    genre: "Thriller",
    rating: 6.5,
    imdbRating: 6.5,
    year: 2017,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Gerald's+Game",
  },
  {
    id: 76,
    title: "I Care a Lot",
    description:
      "A court-appointed legal guardian defrauds her older clients and traps them under her care. But her latest mark comes with some unexpected baggage.",
    genre: "Thriller",
    rating: 6.3,
    imdbRating: 6.3,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=I+Care+a+Lot",
  },
  {
    id: 77,
    title: "Windfall",
    description:
      "A man breaks into a tech billionaire's empty vacation home, but things go sideways when the arrogant mogul and his wife arrive for a last-minute getaway.",
    genre: "Thriller",
    rating: 5.7,
    imdbRating: 5.7,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Windfall",
  },
  {
    id: 78,
    title: "The Unforgivable",
    description:
      "Released from prison after serving a sentence for a violent crime, Ruth Slater (Sandra Bullock) re-enters a society that refuses to forgive her past.",
    genre: "Thriller",
    rating: 7.1,
    imdbRating: 7.1,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Unforgivable",
  },
  {
    id: 79,
    title: "Spiderhead",
    description:
      "In a state-of-the-art penitentiary, a pharmaceutical genius experiments on inmates with emotion-controlling drugs.",
    genre: "Thriller",
    rating: 5.4,
    imdbRating: 5.4,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Spiderhead",
  },
  {
    id: 80,
    title: "Hold the Dark",
    description:
      "After the deaths of three children suspected to be killed by wolves, writer Russell Core is hired by the parents of a missing six-year-old boy to track down and locate their son in the Alaskan wilderness.",
    genre: "Thriller",
    rating: 5.6,
    imdbRating: 5.6,
    year: 2018,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Hold+the+Dark",
  },

  // War
  {
    id: 151,
    title: "All Quiet on the Western Front",
    description:
      "A young German soldier's terrifying experiences and distress on the western front during World War I.",
    genre: "War",
    rating: 7.8,
    imdbRating: 7.8,
    year: 2022,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=All+Quiet+on+Western+Front",
  },
  {
    id: 152,
    title: "Da 5 Bloods",
    description:
      "Four African American vets battle the forces of man and nature when they return to Vietnam seeking the remains of their fallen squad leader and the gold fortune he helped them hide.",
    genre: "War",
    rating: 6.5,
    imdbRating: 6.5,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Da+5+Bloods",
  },
  {
    id: 153,
    title: "The Forgotten Battle",
    description:
      "During WWII's crucial Battle of the Scheldt, the lives of a glider pilot, a Nazi soldier and a reluctant Resistance recruit tragically intersect.",
    genre: "War",
    rating: 7.1,
    imdbRating: 7.1,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Forgotten+Battle",
  },
  {
    id: 154,
    title: "Munich: The Edge of War",
    description:
      "At the tense 1938 Munich Conference, former friends who now work for opposing governments become reluctant spies racing to expose a Nazi secret.",
    genre: "War",
    rating: 6.8,
    imdbRating: 6.8,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Munich:+Edge+of+War",
  },
  {
    id: 155,
    title: "Operation Mincemeat",
    description: "During WWII, two intelligence officers use a corpse and false papers to outwit German troops.",
    genre: "War",
    rating: 6.6,
    imdbRating: 6.6,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Operation+Mincemeat",
  },
  {
    id: 156,
    title: "Siege of Jadotville",
    description:
      "Besieged by overwhelming enemy forces, Irish soldiers on a U.N. peacekeeping mission in Africa valiantly defend their outpost in this true story.",
    genre: "War",
    rating: 7.2,
    imdbRating: 7.2,
    year: 2016,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Siege+of+Jadotville",
  },
  {
    id: 157,
    title: "War Machine",
    description:
      "When a proud general is tasked with winning an unpopular war, he takes the challenge head-on, not knowing that hubris may be his own worst enemy.",
    genre: "War",
    rating: 6.0,
    imdbRating: 6.0,
    year: 2017,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=War+Machine",
  },
  {
    id: 158,
    title: "Sand Castle",
    description:
      "After the invasion of Iraq in 2003, a reluctant soldier's platoon is dispatched on a dangerous mission to repair a hostile village's water system.",
    genre: "War",
    rating: 6.3,
    imdbRating: 6.3,
    year: 2017,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Sand+Castle",
  },
  {
    id: 159,
    title: "Outlaw King",
    description:
      "After being crowned King of Scotland, legendary warrior Robert the Bruce is forced into exile by the English and leads a band of outlaws to help him reclaim the throne.",
    genre: "War",
    rating: 6.9,
    imdbRating: 6.9,
    year: 2018,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Outlaw+King",
  },
  {
    id: 160,
    title: "The King",
    description:
      "Hal, wayward prince and heir to the English throne, is crowned King Henry V after his tyrannical father dies. Now the young king must navigate palace politics, the war his father left behind, and the emotional strings of his past life.",
    genre: "War",
    rating: 7.2,
    imdbRating: 7.2,
    year: 2019,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+King",
  },

  // Western
  {
    id: 161,
    title: "The Harder They Fall",
    description:
      "When an outlaw discovers his enemy is being released from prison, he reunites his gang to seek revenge in this Western.",
    genre: "Western",
    rating: 6.6,
    imdbRating: 6.6,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Harder+They+Fall",
  },
  {
    id: 162,
    title: "The Power of the Dog",
    description:
      "Charismatic rancher Phil Burbank inspires fear and awe in those around him. When his brother brings home a new wife and her son, Phil torments them until he finds himself exposed to the possibility of love.",
    genre: "Western",
    rating: 6.9,
    imdbRating: 6.8,
    year: 2021,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Power+of+the+Dog",
  },
  {
    id: 163,
    title: "The Ballad of Buster Scruggs",
    description:
      "Six tales of life and violence in the Old West, following a singing gunslinger, a bank robber, a traveling impresario, an elderly prospector, a wagon train, and a perverse pair of bounty hunters.",
    genre: "Western",
    rating: 7.3,
    imdbRating: 7.3,
    year: 2018,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Ballad+of+Buster+Scruggs",
  },
  {
    id: 164,
    title: "Godless",
    description:
      "In the 1880s American West, a notorious outlaw and his gang hunt for the ex-protégé who betrayed them, while he seeks refuge in a town inhabited only by women.",
    genre: "Western",
    rating: 8.3,
    imdbRating: 8.3,
    year: 2017,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Godless",
  },
  {
    id: 165,
    title: "The Ridiculous 6",
    description:
      "An outlaw who was raised by Native Americans discovers that he has five half-brothers; together the men go on a mission to find their wayward, deadbeat dad.",
    genre: "Western",
    rating: 4.8,
    imdbRating: 4.8,
    year: 2015,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Ridiculous+6",
  },
  {
    id: 166,
    title: "Hostiles",
    description:
      "In 1892, a legendary Army Captain reluctantly agrees to escort a Cheyenne chief and his family through dangerous territory.",
    genre: "Western",
    rating: 7.2,
    imdbRating: 7.2,
    year: 2017,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Hostiles",
  },
  {
    id: 167,
    title: "The Outsider",
    description:
      "An American soldier imprisoned in postwar Japan enters the dark world of the yakuza, adopting their way of life in repayment for his freedom.",
    genre: "Western",
    rating: 6.3,
    imdbRating: 6.3,
    year: 2018,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Outsider",
  },
  {
    id: 168,
    title: "Hell or High Water",
    description:
      "A divorced father and his ex-con older brother resort to a desperate scheme in order to save their family's ranch in West Texas.",
    genre: "Western",
    rating: 7.6,
    imdbRating: 7.6,
    year: 2016,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=Hell+or+High+Water",
  },
  {
    id: 169,
    title: "News of the World",
    description:
      "A Civil War veteran agrees to deliver a girl, taken by the Kiowa people years ago, to her aunt and uncle, against her will. They travel hundreds of miles and face grave dangers as they search for a place that either can call home.",
    genre: "Western",
    rating: 6.8,
    imdbRating: 6.8,
    year: 2020,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=News+of+the+World",
  },
  {
    id: 170,
    title: "The Hateful Eight",
    description:
      "In the dead of a Wyoming winter, a bounty hunter and his prisoner find shelter in a cabin currently inhabited by a collection of nefarious characters.",
    genre: "Western",
    rating: 7.8,
    imdbRating: 7.8,
    year: 2015,
    imageUrl: "https://placehold.co/500x300/262626/E50914?text=The+Hateful+Eight",
  },
]
